name: On Push

on: push

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: make install
      - name: run eslint
        run: make lint
